#! ruby
require 'test/unit'
require 'super_random'

class TestSuperRandom < Test::Unit::TestCase
  def test_256
    super_random = SuperRandom.new

    bytes = super_random.bytes(256)
    assert_equal 256, bytes.length, 'Number of  bytes:'
    assert_equal 4, super_random.services, 'Number of services:'
    assert_equal 3.03125, super_random.randomness, 'Measure of "hyper" radomness:'
  end
end
