#! ruby
require 'test/unit'
require 'super_random'

class TestBytes < Test::Unit::TestCase
  def test_64_bytes
    sleep 1 # Rate limit HTTP sources

    super_random = SuperRandom.new

    bytes = super_random.bytes
    assert_equal 64, bytes.length, 'Number of  bytes:'
    assert_equal 1, super_random.source_count, 'Number of sources:'
    assert_equal 210, super_random.byte_count, 'Byte count:'
  end
end
